DEPFIND="$HOME/Code/sandbox/dependency-finder/bin/DependencyExtractor -xml -out "
# cd actor && $DEPFIND actor.xml
# cd ../ambari && $DEPFIND ambari.xml
# cd ../Anki-Android && $DEPFIND Anki-Android.xml
# cd ../atmosphere && $DEPFIND atmosphere.xml
# cd ../basex && $DEPFIND basex.xml
# cd ../bazel && $DEPFIND bazel.xml
# cd ../bbb && $DEPFIND bbb.xml
# cd ../BroadLeafCommerce && $DEPFIND BroadLeafCommerce.xml
# cd ../buck && $DEPFIND buck.xml
# cd ../camel && $DEPFIND camel.xml
# cd ../cas && $DEPFIND cas.xml
# cd ../cassandra && $DEPFIND cassandra.xml
# cd ../cgeo && $DEPFIND cgeo.xml
# cd ../closure-compiler && $DEPFIND closure-compiler.xml
# cd ../cloudstack && $DEPFIND cloudstack.xml
# cd ../corenlp && $DEPFIND corenlp.xml
# cd ../dbeaver && $DEPFIND dbeaver.xml
# cd ../deeplearning4j && $DEPFIND deeplearning4j.xml
# cd ../depfind.sh && $DEPFIND depfind.sh.xml
# cd ../drools && $DEPFIND drools.xml
# cd ../druid && $DEPFIND druid.xml
# cd ../elasticsearch && $DEPFIND elasticsearch.xml
# cd ../fabric8 && $DEPFIND fabric8.xml
# cd ../fbreaderj && $DEPFIND fbreaderj.xml
# cd ../flink && $DEPFIND flink.xml
# cd ../geoserver && $DEPFIND geoserver.xml
# cd ../geotools && $DEPFIND geotools.xml
# cd ../gradle && $DEPFIND gradle.xml
# cd ../grails && $DEPFIND grails.xml
# cd ../groovy && $DEPFIND groovy.xml
# cd ../gwt && $DEPFIND gwt.xml
# cd ../h2o-3 && $DEPFIND h2o-3.xml
# cd ../hazelcast && $DEPFIND hazelcast.xml
# cd ../hbase && $DEPFIND hbase.xml
# cd ../hibernate && $DEPFIND hibernate.xml
# cd ../hive && $DEPFIND hive.xml
# cd ../i2p && $DEPFIND i2p.xml
# cd ../idea && $DEPFIND idea.xml
# cd ../ignite && $DEPFIND ignite.xml
# cd ../isis && $DEPFIND isis.xml
# cd ../jabref && $DEPFIND jabref.xml
# cd jetty && $DEPFIND jetty.xml
# cd ../jitsi && $DEPFIND jitsi.xml
# cd ../jmeter && $DEPFIND jmeter.xml
# cd ../jmonkeyengine && $DEPFIND jmonkeyengine.xml
# cd ../kaa && $DEPFIND kaa.xml
# cd ../keycloak && $DEPFIND keycloak.xml
# cd ../killbill && $DEPFIND killbill.xml
# cd ../kotlinc && $DEPFIND kotlinc.xml
# cd ../kylin && $DEPFIND kylin.xml
# cd ../languagetool && $DEPFIND languagetool.xml
# cd ../libgdx && $DEPFIND libgdx.xml
# cd ../liferay-portal && $DEPFIND liferay-portal.xml
# cd ../liquibase && $DEPFIND liquibase.xml
# cd ../minecraftforge && $DEPFIND minecraftforge.xml
# cd ../mps && $DEPFIND mps.xml
# cd ../mule && $DEPFIND mule.xml
# cd ../neo4j && $DEPFIND neo4j.xml
# cd ../ofbiz && $DEPFIND ofbiz.xml
# cd ../opencms && $DEPFIND opencms.xml
# cd ../openfire && $DEPFIND openfire.xml
# cd ../openhab && $DEPFIND openhab.xml
# cd ../openmrs && $DEPFIND openmrs.xml
# cd ../opentripplanner && $DEPFIND opentripplanner.xml
# cd ../optaplanner && $DEPFIND optaplanner.xml
# cd ../orientdb && $DEPFIND orientdb.xml
# cd ../osmand && $DEPFIND osmand.xml
# cd ../owncloud && $DEPFIND owncloud.xml
# cd ../pentaho && $DEPFIND pentaho.xml
# cd ../pinpoint && $DEPFIND pinpoint.xml
# cd ../presto && $DEPFIND presto.xml
# cd ../processing && $DEPFIND processing.xml
# cd ../react-native && $DEPFIND react-native.xml
# cd ../restlet && $DEPFIND restlet.xml
# cd ../soapui && $DEPFIND soapui.xml
# cd ../solr && $DEPFIND solr.xml
# cd ../sonarqube && $DEPFIND sonarqube.xml
# cd ../spring-framework && $DEPFIND spring-framework.xml
# cd ../storm && $DEPFIND storm.xml
# cd ../structr && $DEPFIND structr.xml
# cd ../terasology && $DEPFIND terasology.xml
# cd ../usergrid && $DEPFIND usergrid.xml
cd usergrid-java && $DEPFIND usergrid-java.xml
cd ../vaadin && $DEPFIND vaadin.xml
cd ../voltdb && $DEPFIND voltdb.xml
cd ../wicket && $DEPFIND wicket.xml
cd ../wildfly && $DEPFIND wildfly.xml
cd ../wordpress-android && $DEPFIND wordpress-android.xml
