# depfind-converter actor/actor.xml > actor/actor.mdg && 
#     depfind-converter --inheritance actor/actor.xml > actor/actor-inheritance.txt
# depfind-converter ambari/ambari.xml > ambari/ambari.mdg && 
#     depfind-converter --inheritance ambari/ambari.xml > ambari/ambari-inheritance.txt
# depfind-converter Anki-Android/Anki-Android.xml > Anki-Android/Anki-Android.mdg && 
#     depfind-converter --inheritance Anki-Android/Anki-Android.xml > Anki-Android/Anki-Android-inheritance.txt
# depfind-converter atmosphere/atmosphere.xml > atmosphere/atmosphere.mdg && 
#     depfind-converter --inheritance atmosphere/atmosphere.xml > atmosphere/atmosphere-inheritance.txt
# depfind-converter basex/basex.xml > basex/basex.mdg && 
#     depfind-converter --inheritance basex/basex.xml > basex/basex-inheritance.txt
# depfind-converter bazel/bazel.xml > bazel/bazel.mdg && 
#     depfind-converter --inheritance bazel/bazel.xml > bazel/bazel-inheritance.txt
# depfind-converter bbb/bbb.xml > bbb/bbb.mdg && 
#     depfind-converter --inheritance bbb/bbb.xml > bbb/bbb-inheritance.txt
# depfind-converter BroadLeafCommerce/BroadLeafCommerce.xml > BroadLeafCommerce/BroadLeafCommerce.mdg && 
#     depfind-converter --inheritance BroadLeafCommerce/BroadLeafCommerce.xml > BroadLeafCommerce/BroadLeafCommerce-inheritance.txt
# depfind-converter buck/buck.xml > buck/buck.mdg && 
#     depfind-converter --inheritance buck/buck.xml > buck/buck-inheritance.txt
# depfind-converter camel/camel.xml > camel/camel.mdg && 
#     depfind-converter --inheritance camel/camel.xml > camel/camel-inheritance.txt
# depfind-converter cas/cas.xml > cas/cas.mdg && 
#     depfind-converter --inheritance cas/cas.xml > cas/cas-inheritance.txt
# depfind-converter cassandra/cassandra.xml > cassandra/cassandra.mdg && 
#     depfind-converter --inheritance cassandra/cassandra.xml > cassandra/cassandra-inheritance.txt
# depfind-converter cgeo/cgeo.xml > cgeo/cgeo.mdg && 
#     depfind-converter --inheritance cgeo/cgeo.xml > cgeo/cgeo-inheritance.txt
# depfind-converter closure-compiler/closure-compiler.xml > closure-compiler/closure-compiler.mdg && 
#     depfind-converter --inheritance closure-compiler/closure-compiler.xml > closure-compiler/closure-compiler-inheritance.txt
# depfind-converter cloudstack/cloudstack.xml > cloudstack/cloudstack.mdg && 
#     depfind-converter --inheritance cloudstack/cloudstack.xml > cloudstack/cloudstack-inheritance.txt
# depfind-converter corenlp/corenlp.xml > corenlp/corenlp.mdg && 
#     depfind-converter --inheritance corenlp/corenlp.xml > corenlp/corenlp-inheritance.txt
# depfind-converter dbeaver/dbeaver.xml > dbeaver/dbeaver.mdg && 
#     depfind-converter --inheritance dbeaver/dbeaver.xml > dbeaver/dbeaver-inheritance.txt
# depfind-converter deeplearning4j/deeplearning4j.xml > deeplearning4j/deeplearning4j.mdg && 
#     depfind-converter --inheritance deeplearning4j/deeplearning4j.xml > deeplearning4j/deeplearning4j-inheritance.txt
# depfind-converter drools/drools.xml > drools/drools.mdg && 
#     depfind-converter --inheritance drools/drools.xml > drools/drools-inheritance.txt
# depfind-converter druid/druid.xml > druid/druid.mdg && 
#     depfind-converter --inheritance druid/druid.xml > druid/druid-inheritance.txt
# depfind-converter elasticsearch/elasticsearch.xml > elasticsearch/elasticsearch.mdg && 
#     depfind-converter --inheritance elasticsearch/elasticsearch.xml > elasticsearch/elasticsearch-inheritance.txt
# depfind-converter fabric8/fabric8.xml > fabric8/fabric8.mdg && 
#     depfind-converter --inheritance fabric8/fabric8.xml > fabric8/fabric8-inheritance.txt
# depfind-converter fbreaderj/fbreaderj.xml > fbreaderj/fbreaderj.mdg && 
#     depfind-converter --inheritance fbreaderj/fbreaderj.xml > fbreaderj/fbreaderj-inheritance.txt
# depfind-converter flink/flink.xml > flink/flink.mdg && 
#     depfind-converter --inheritance flink/flink.xml > flink/flink-inheritance.txt
# depfind-converter geoserver/geoserver.xml > geoserver/geoserver.mdg && 
#     depfind-converter --inheritance geoserver/geoserver.xml > geoserver/geoserver-inheritance.txt
# depfind-converter geotools/geotools.xml > geotools/geotools.mdg && 
#     depfind-converter --inheritance geotools/geotools.xml > geotools/geotools-inheritance.txt
# depfind-converter gradle/gradle.xml > gradle/gradle.mdg && 
#     depfind-converter --inheritance gradle/gradle.xml > gradle/gradle-inheritance.txt
# depfind-converter grails/grails.xml > grails/grails.mdg && 
#     depfind-converter --inheritance grails/grails.xml > grails/grails-inheritance.txt
# depfind-converter groovy/groovy.xml > groovy/groovy.mdg && 
#     depfind-converter --inheritance groovy/groovy.xml > groovy/groovy-inheritance.txt
# depfind-converter gwt/gwt.xml > gwt/gwt.mdg && 
#     depfind-converter --inheritance gwt/gwt.xml > gwt/gwt-inheritance.txt
# depfind-converter h2o-3/h2o-3.xml > h2o-3/h2o-3.mdg && 
#     depfind-converter --inheritance h2o-3/h2o-3.xml > h2o-3/h2o-3-inheritance.txt
# depfind-converter hazelcast/hazelcast.xml > hazelcast/hazelcast.mdg && 
#     depfind-converter --inheritance hazelcast/hazelcast.xml > hazelcast/hazelcast-inheritance.txt
# depfind-converter hbase/hbase.xml > hbase/hbase.mdg && 
#     depfind-converter --inheritance hbase/hbase.xml > hbase/hbase-inheritance.txt
# depfind-converter hibernate/hibernate.xml > hibernate/hibernate.mdg && 
#     depfind-converter --inheritance hibernate/hibernate.xml > hibernate/hibernate-inheritance.txt
# depfind-converter hive/hive.xml > hive/hive.mdg && 
#     depfind-converter --inheritance hive/hive.xml > hive/hive-inheritance.txt
# depfind-converter i2p/i2p.xml > i2p/i2p.mdg && 
#     depfind-converter --inheritance i2p/i2p.xml > i2p/i2p-inheritance.txt
# depfind-converter idea/idea.xml > idea/idea.mdg && 
#     depfind-converter --inheritance idea/idea.xml > idea/idea-inheritance.txt
# depfind-converter ignite/ignite.xml > ignite/ignite.mdg && 
#     depfind-converter --inheritance ignite/ignite.xml > ignite/ignite-inheritance.txt
# depfind-converter isis/isis.xml > isis/isis.mdg && 
#     depfind-converter --inheritance isis/isis.xml > isis/isis-inheritance.txt
# depfind-converter jabref/jabref.xml > jabref/jabref.mdg && 
#     depfind-converter --inheritance jabref/jabref.xml > jabref/jabref-inheritance.txt
# depfind-converter jetty/jetty.xml > jetty/jetty.mdg && 
#     depfind-converter --inheritance jetty/jetty.xml > jetty/jetty-inheritance.txt
# depfind-converter jitsi/jitsi.xml > jitsi/jitsi.mdg && 
#     depfind-converter --inheritance jitsi/jitsi.xml > jitsi/jitsi-inheritance.txt
# depfind-converter jmeter/jmeter.xml > jmeter/jmeter.mdg && 
#     depfind-converter --inheritance jmeter/jmeter.xml > jmeter/jmeter-inheritance.txt
# depfind-converter jmonkeyengine/jmonkeyengine.xml > jmonkeyengine/jmonkeyengine.mdg && 
#     depfind-converter --inheritance jmonkeyengine/jmonkeyengine.xml > jmonkeyengine/jmonkeyengine-inheritance.txt
# depfind-converter kaa/kaa.xml > kaa/kaa.mdg && 
#     depfind-converter --inheritance jooq/jooq.xml > jooq/jooq-inheritance.txt
# depfind-converter jooq/jooq.xml > jooq/jooq.mdg && 
#     depfind-converter --inheritance kaa/kaa.xml > kaa/kaa-inheritance.txt
# depfind-converter keycloak/keycloak.xml > keycloak/keycloak.mdg && 
#     depfind-converter --inheritance keycloak/keycloak.xml > keycloak/keycloak-inheritance.txt
# depfind-converter killbill/killbill.xml > killbill/killbill.mdg && 
#     depfind-converter --inheritance killbill/killbill.xml > killbill/killbill-inheritance.txt
# depfind-converter kotlinc/kotlinc.xml > kotlinc/kotlinc.mdg && 
#     depfind-converter --inheritance kotlinc/kotlinc.xml > kotlinc/kotlinc-inheritance.txt
# depfind-converter kylin/kylin.xml > kylin/kylin.mdg && 
#     depfind-converter --inheritance kylin/kylin.xml > kylin/kylin-inheritance.txt
# depfind-converter languagetool/languagetool.xml > languagetool/languagetool.mdg && 
#     depfind-converter --inheritance languagetool/languagetool.xml > languagetool/languagetool-inheritance.txt
# depfind-converter libgdx/libgdx.xml > libgdx/libgdx.mdg && 
#     depfind-converter --inheritance libgdx/libgdx.xml > libgdx/libgdx-inheritance.txt
# depfind-converter liferay-portal/liferay-portal.xml > liferay-portal/liferay-portal.mdg && 
#     depfind-converter --inheritance liferay-portal/liferay-portal.xml > liferay-portal/liferay-portal-inheritance.txt
# depfind-converter liquibase/liquibase.xml > liquibase/liquibase.mdg && 
    # depfind-converter --inheritance liquibase/liquibase.xml > liquibase/liquibase-inheritance.txt
# depfind-converter minecraftforge/minecraftforge.xml > minecraftforge/minecraftforge.mdg && 
#     depfind-converter --inheritance minecraftforge/minecraftforge.xml > minecraftforge/minecraftforge-inheritance.txt
# depfind-converter mps/mps.xml > mps/mps.mdg && 
#     depfind-converter --inheritance mps/mps.xml > mps/mps-inheritance.txt
# depfind-converter mule/mule.xml > mule/mule.mdg && 
#     depfind-converter --inheritance mule/mule.xml > mule/mule-inheritance.txt
# depfind-converter neo4j/neo4j.xml > neo4j/neo4j.mdg && 
#     depfind-converter --inheritance neo4j/neo4j.xml > neo4j/neo4j-inheritance.txt
# depfind-converter ofbiz/ofbiz.xml > ofbiz/ofbiz.mdg && 
#     depfind-converter --inheritance ofbiz/ofbiz.xml > ofbiz/ofbiz-inheritance.txt
# depfind-converter opencms/opencms.xml > opencms/opencms.mdg && 
#     depfind-converter --inheritance opencms/opencms.xml > opencms/opencms-inheritance.txt
# depfind-converter openfire/openfire.xml > openfire/openfire.mdg && 
#     depfind-converter --inheritance openfire/openfire.xml > openfire/openfire-inheritance.txt
# depfind-converter openhab/openhab.xml > openhab/openhab.mdg && 
#     depfind-converter --inheritance openhab/openhab.xml > openhab/openhab-inheritance.txt
# depfind-converter openmrs/openmrs.xml > openmrs/openmrs.mdg && 
#     depfind-converter --inheritance openmrs/openmrs.xml > openmrs/openmrs-inheritance.txt
# depfind-converter opentripplanner/opentripplanner.xml > opentripplanner/opentripplanner.mdg && 
#     depfind-converter --inheritance opentripplanner/opentripplanner.xml > opentripplanner/opentripplanner-inheritance.txt
# depfind-converter optaplanner/optaplanner.xml > optaplanner/optaplanner.mdg && 
#     depfind-converter --inheritance optaplanner/optaplanner.xml > optaplanner/optaplanner-inheritance.txt
# depfind-converter orientdb/orientdb.xml > orientdb/orientdb.mdg && 
#     depfind-converter --inheritance orientdb/orientdb.xml > orientdb/orientdb-inheritance.txt
# depfind-converter osmand/osmand.xml > osmand/osmand.mdg && 
#     depfind-converter --inheritance osmand/osmand.xml > osmand/osmand-inheritance.txt
# depfind-converter owncloud/owncloud.xml > owncloud/owncloud.mdg && 
#     depfind-converter --inheritance owncloud/owncloud.xml > owncloud/owncloud-inheritance.txt
# depfind-converter pentaho/pentaho.xml > pentaho/pentaho.mdg && 
#     depfind-converter --inheritance pentaho/pentaho.xml > pentaho/pentaho-inheritance.txt
# depfind-converter pinpoint/pinpoint.xml > pinpoint/pinpoint.mdg && 
#     depfind-converter --inheritance pinpoint/pinpoint.xml > pinpoint/pinpoint-inheritance.txt
# depfind-converter presto/presto.xml > presto/presto.mdg && 
#     depfind-converter --inheritance presto/presto.xml > presto/presto-inheritance.txt
# depfind-converter processing/processing.xml > processing/processing.mdg && 
#     depfind-converter --inheritance processing/processing.xml > processing/processing-inheritance.txt
# depfind-converter react-native/react-native.xml > react-native/react-native.mdg && 
#     depfind-converter --inheritance react-native/react-native.xml > react-native/react-native-inheritance.txt
# depfind-converter restlet/restlet.xml > restlet/restlet.mdg && 
#     depfind-converter --inheritance restlet/restlet.xml > restlet/restlet-inheritance.txt
# depfind-converter soapui/soapui.xml > soapui/soapui.mdg && 
#     depfind-converter --inheritance soapui/soapui.xml > soapui/soapui-inheritance.txt
# depfind-converter solr/solr.xml > solr/solr.mdg && 
#     depfind-converter --inheritance solr/solr.xml > solr/solr-inheritance.txt
# depfind-converter sonarqube/sonarqube.xml > sonarqube/sonarqube.mdg && 
#     depfind-converter --inheritance sonarqube/sonarqube.xml > sonarqube/sonarqube-inheritance.txt
# depfind-converter spring-framework/spring-framework.xml > spring-framework/spring-framework.mdg && 
#     depfind-converter --inheritance spring-framework/spring-framework.xml > spring-framework/spring-framework-inheritance.txt
# depfind-converter storm/storm.xml > storm/storm.mdg && 
#     depfind-converter --inheritance storm/storm.xml > storm/storm-inheritance.txt
# depfind-converter structr/structr.xml > structr/structr.mdg && 
#     depfind-converter --inheritance structr/structr.xml > structr/structr-inheritance.txt
# depfind-converter terasology/terasology.xml > terasology/terasology.mdg && 
#     depfind-converter --inheritance terasology/terasology.xml > terasology/terasology-inheritance.txt
# depfind-converter usergrid/usergrid.xml > usergrid/usergrid.mdg && 
#     depfind-converter --inheritance usergrid/usergrid.xml > usergrid/usergrid-inheritance.txt
# depfind-converter usergrid-java/usergrid-java.xml > usergrid-java/usergrid-java.mdg && 
#     depfind-converter --inheritance usergrid-java/usergrid-java.xml > usergrid-java/usergrid-java-inheritance.txt
# depfind-converter vaadin/vaadin.xml > vaadin/vaadin.mdg && 
#     depfind-converter --inheritance vaadin/vaadin.xml > vaadin/vaadin-inheritance.txt
depfind-converter voltdb/voltdb.xml > voltdb/voltdb.mdg && 
    depfind-converter --inheritance voltdb/voltdb.xml > voltdb/voltdb-inheritance.txt
depfind-converter wicket/wicket.xml > wicket/wicket.mdg && 
    depfind-converter --inheritance wicket/wicket.xml > wicket/wicket-inheritance.txt
depfind-converter wildfly/wildfly.xml > wildfly/wildfly.mdg && 
    depfind-converter --inheritance wildfly/wildfly.xml > wildfly/wildfly-inheritance.txt
depfind-converter wordpress-android/wordpress-android.xml > wordpress-android/wordpress-android.mdg && 
    depfind-converter --inheritance wordpress-android/wordpress-android.xml > wordpress-android/wordpress-android-inheritance.txt